---
- name: IaaS Provisioning
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp    
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: 10.44.77.27
      nutanix_username: admin
      nutanix_password: Nutanix.123
      validate_certs: false
  tasks:
    - name: Include vars file
      include_vars:
        file: vars.yml
    - include_role:
        name: external_subnet
    - include_role:
        name: vpc
    - include_role:
        name: static_route
    - include_role:
        name: overlay_subnet
    - include_role:
        name: vm
    - include_role:
        name: fip
