---
- name: Create "{{ item.name }}" VM
  nutanix.ncp.ntnx_vms:
    state: present
    name: "{{ item.name }}"
    desc: "{{ item.desc }}"
    cluster:
      name: "{{ cluster.name }}"
    networks:
      - is_connected: "{{ item.is_connected }}"
        subnet:
          name: "{{ item.subnet_name }}"
        private_ip: "{{ item.private_ip }}"
    disks:
      - type: DISK
        size_gb: 30
        bus: SATA
        clone_image:
          name: "{{ item.image_name }}"
  register: vm
- ansible.builtin.debug:
    msg:
      - "name: {{ vm.response.status.name }}"
      - "uuid: {{ vm.vm_uuid }}"
